version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-to-dokku:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: |
          rm -rf .git
          git init
          git add .
          git commit -m "init from circle-ci"
      - run:
          name: Add dokku remote
          command: git remote add dokku ssh://dokku@64.225.14.46:portal-server
      - run:
          name: Push to dokku
          command: git push dokku master
workflows:
    deployment:
      jobs:
        - build-and-test
        - deploy-to-dokku:
            requires:
              - build-and-test